<a href="https://colab.research.google.com/github/Probin1904/NIELIT-ASSIGNMENTS/blob/main/Probin_Kumar_Jena.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Name:Probin Kumar Jena
# Course: Python with Data Science And Machine Learning (4-weeks)

# **Assingment:1**

Q1. Declare and Print

In [ ]:
Name = "Probin Kumar Jena"
Course = "Python With Data Science and Machine Learning (4 Weeks)"
Assignment = "Assignment:1"
Question = "Q1 Declare and Print"

print(f"Name - {Name}")
print(f"Course - {Course}")
print(f"{Assignment}")
print(f"{Question}")

Name - Probin Kumar Jena
Course - Python With Data Science and Machine Learning (4 Weeks)
Assignment:1
Q1 Declare and Print


Q2. Swap Two Numbers

In [ ]:
a = 5
b = 10
a, b = b, a
print("a =", a)
print("b =", b)


a = 10
b = 5


Q3. Arithmetic Operations

In [7]:
a = 7
b = 2

print("Sum: ", a + b)
print("Subtraction: ", a - b)
print("Multiplication: ", a * b)
print("Division: ", a / b)
print("Floor Division: ", a // b)
print("Modulo: ", a % b)
print("Power: ", a ** b)


Sum:  9
Subtraction:  5
Multiplication:  14
Division:  3.5
Floor Division:  3
Modulo:  1
Power:  49


Q4.Percentage Calculation

In [ ]:
Physics = int(input("Enter the marks of Physics: "))
Chemistry = int(input("Enter the marks of Chemistry: "))
Maths = int(input("Enter the marks of Maths: "))
English = int(input("Enter the marks of English: "))
Computer_Science = int(input("Enter the marks of Computer Science: "))

Total = Physics + Chemistry + Maths + English + Computer_Science

Percentage = (Total / 500) * 100

print(f"Total Marks: {Total}")
print(f"Percentage: {Percentage}%")

Enter the marks of Physics: 89
Enter the marks of Chemistry: 66
Enter the marks of Maths: 70
Enter the marks of English: 87
Enter the marks of Computer Science: 85
Total Marks: 397
Percentage: 79.4%


Q5.Compound Assignment Operator

In [ ]:
x = 10

x += 5
print("After x += 5: ", x)

x -= 3
print("After x -= 3: ", x)

x *= 2
print("After x *= 2: ", x)

x /= 4
print("After x /= 4: ", x)

x //= 2
print("After x //= 2: ", x)

x **= 2
print("After x **= 2: ", x)


After x += 5:  15
After x -= 3:  12
After x *= 2:  24
After x /= 4:  6.0
After x //= 2:  3.0
After x **= 2:  9.0


Q6. Relational Operator

In [ ]:
a = 33
b = 20

print(a == b)
print(a != b)
print(a > b)
print(a < b)
print(a >= b)
print(a <= b)


False
True
True
False
True
False


Q7. Logical Operator

In [ ]:
age = int(input("Enter your age: "))
has_ticket = input("Do you have a ticket? (yes/no): ").lower() == "yes"

if age >= 18 and has_ticket:
    print("Welcome aboard! You are eligible for the ride.")
elif age < 18 and has_ticket:
    print("Sorry, you must be at least 18 years old to ride.")
elif not has_ticket:
    print("Please purchase a ticket before boarding.")
else:
    print("Invalid input.")


Enter your age: 21
Do you have a ticket? (yes/no): yes
Welcome aboard! You are eligible for the ride.


Q8. Identity Operator

In [ ]:
x = [1, 2, 3]
y = [1, 2, 3]
z = x

print(x is y)
print(x is z)
print(x is not y)
print(x is not z)



False
True
True
False


Q9. Bitwise Operator


In [ ]:
a = int(input("Enter the value of a: "))
b = int(input("Enter the value of b: "))

print(f"a & b: {a & b}")
print(f"a | b: {a | b}")
print(f"a ^ b: {a ^ b}")
print(f"~a: {~a}")
print(f"a << 2: {a << 2}")
print(f"a >> 2: {a >> 2}")


Enter the value of a: 34
Enter the value of b: 27
a & b: 2
a | b: 59
a ^ b: 57
~a: -35
a << 2: 136
a >> 2: 8


Q10. Variable Types and Typecasting

In [ ]:
a = 10
b = 3.5
c = "Hello"
d = True

# User input and typecasting
num = int(input("Enter a number: "))
price = float(input("Enter price: "))

# Type checking and conversion
print(type(a), type(b), type(c), type(d))
print("Number as string:", str(num))
print("Price as integer:", int(price))



Enter a number: 10
Enter price: 35
<class 'int'> <class 'float'> <class 'str'> <class 'bool'>
Number as string: 10
Price as integer: 35


# **Assignment:2**

Q1. Write a program to print number from 1 to 10 stop loop when number reach 9.

In [ ]:
for num in range(1, 11):  # 1 to 10 inclusive
    print(num)
    if num == 9:
        break


1
2
3
4
5
6
7
8
9


Q2. Write a program that keep asking the user to enter the number and stop when
user enters a negative number.

In [ ]:
while True:
    num = float(input("Enter a number (enter a negative number to stop): "))
    if num < 0:
        break


Enter a number (enter a negative number to stop): -34


Q3. Write a program to find first even number in a list using for loop and break

In [ ]:
numbers = [5, 3, 7, 2, 9, 6, 4]

for num in numbers:
    if num % 2 == 0:
        print("First even number:", num)
        break


First even number: 2


Q4. Keep adding number onwards until total sum exceeds 25 print last sum and digit.

In [ ]:
total_sum = int(input("Enter the initial sum: "))
digit = int(input("Enter the initial digit: "))

while total_sum <= 25:
  digit += 1
  total_sum += digit

print(f"Last sum: {total_sum}")
print(f"Last digit: {digit}")

Enter the initial sum: 7
Enter the initial digit: 12
Last sum: 34
Last digit: 14


Q5. Keep asking the user to guess the password until they guess admin123, use while and break.

In [ ]:
while True:
    password_guess = input("Guess the password: ")
    if password_guess == "admin123":
        print("Correct password!")
        break
    else:
        print("Incorrect password. Try again.")

Guess the password: qw190
Incorrect password. Try again.
Guess the password: 12qwsd
Incorrect password. Try again.
Guess the password: admin1
Incorrect password. Try again.
Guess the password: admin123
Correct password!


Q6.Print multiples of 7 using while loop, stop the value greater than 100.

In [ ]:
i = 7
while i <= 100:
    print(i)
    i += 7


7
14
21
28
35
42
49
56
63
70
77
84
91
98


Q7. Given a number print each digit until a zero is found.

In [ ]:
number = input("Enter a number: ")
for digit in number:
    if digit == '0':
        break
    print(digit)


Enter a number: 123045
1
2
3


# **Assignment:3**

Q1. Take a sentence and reverse the order of its words. Example: "I love Python" → "Python love I"


In [ ]:
sentence = "I love Python"
words = sentence.split()
reversed_sentence = ' '.join(reversed(words))
print(reversed_sentence)


Python love I


Q2. Given a string, count consonants (non-vowel letters, ignoring case). Example: "Hello World" →
7 (H, l, l, W, r, l, d).

In [ ]:
text = input("Enter a string: ")

vowels = "aeiou"
consonant_count = 0

for char in text.lower():
    if char.isalpha() and char not in vowels:
        consonant_count += 1

print("Number of consonants:", consonant_count)

Enter a string: 12
Number of consonants: 0


Q3. Check if two strings are anagrams (same characters, same frequency, ignoring case).


In [20]:
def are_anagrams(s1, s2):
    # Remove non-alphabetic characters and convert to lowercase
    s1_clean = ''.join(ch.lower() for ch in s1 if ch.isalpha())
    s2_clean = ''.join(ch.lower() for ch in s2 if ch.isalpha())
    # Compare sorted strings
    return sorted(s1_clean) == sorted(s2_clean)

str1 = "listen"
str2 = "silent"
print(are_anagrams(str1, str2))

str3 = "Hello"
str4 = "World"
print(are_anagrams(str3, str4))


True
False


Q4. Find the first character in a string that appears only once (case-sensitive). Example: "swiss" →
"w", "programming" → "r".


In [ ]:
def first_unique_char(s):
    frequency = {}
    # Count frequency of each character
    for ch in s:
        if ch in frequency:
            frequency[ch] += 1
        else:
            frequency[ch] = 1
    # Find the first character with frequency 1
    for ch in s:
        if frequency[ch] == 1:
            return ch
    return None

print(first_unique_char("swiss"))
print(first_unique_char("programming"))


w
p


Q5.Compress a string by replacing repeated characters with the character and count. Example:
"aaabbc" → "a3b2c1". If compressed string isn’t shorter, return original.


In [ ]:
def compress_string(s):
    if not s:
        return s
    compressed = []
    current_char = s[0]
    count = 1
    for ch in s[1:]:
        if ch == current_char:
            count += 1
        else:
            compressed.append(f"{current_char}{count}")
            current_char = ch
            count = 1
    compressed.append(f"{current_char}{count}")
    compressed_str = "".join(compressed)
    return compressed_str if len(compressed_str) < len(s) else s

print(compress_string("aaabbc"))
print(compress_string("abc"))
print(compress_string("aabcccccaaa"))


aaabbc
abc
a2b1c5a3


Q6. Find the longest substring in a string that is a palindrome (case-sensitive). Example: "babad" →
"bab" (or "aba"), "cbbd" → "bb". If multiple exist, return the first.

In [ ]:
def longest_palindromic_substring(s):
    if not s or len(s) < 1:
        return ""

    start = 0
    end = 0

    for i in range(len(s)):
        len1 = expand_around_center(s, i, i)       # Odd length
        len2 = expand_around_center(s, i, i + 1)   # Even length
        max_len = max(len1, len2)
        if max_len > end - start:
            start = i - (max_len - 1) // 2
            end = i + max_len // 2

    return s[start:end+1]

def expand_around_center(s, left, right):
    while left >= 0 and right < len(s) and s[left] == s[right]:
        left -= 1
        right += 1
    return right - left - 1

print(longest_palindromic_substring("babad"))
print(longest_palindromic_substring("cbbd"))


aba
bb


Q7. Given a string containing only '(', ')', '{', '}', '[', ']', check if the sequence is valid (properly nested
and closed). Example: "({[]})" → "Valid", "(]" → "Invalid".


In [ ]:
def is_valid(s):
    stack = []
    mapping = {')': '(', '}': '{', ']': '['}
    for char in s:
        if char in mapping:
            if stack and stack[-1] == mapping[char]:
                stack.pop()
            else:
                return False
        else:
            stack.append(char)
    return not stack

s = input("Enter a string: ")
print("Valid" if is_valid(s) else "Invalid")


Enter a string: ({[]})
Valid


Q8. Given a start word, end word, and a list of valid words, find the minimum number of steps to
transform the start word to the end word by changing one letter at a time, where each
intermediate word must be in the list. All words are same length, lowercase. Example:
start="hit", end="cog", wordList=["hot","dot","dog","lot","log","cog"] → 5 (hit → hot → dot → dog →
cog). Return 0 if impossible.

In [19]:
from collections import deque

def ladderLength(beginWord, endWord, wordList):
    wordSet = set(wordList)
    if endWord not in wordSet:
        return 0
    queue = deque([(beginWord, 1)])
    visited = set([beginWord])
    while queue:
        word, steps = queue.popleft()
        if word == endWord:
            return steps
        for i in range(len(word)):
            for c in 'abcdefghijklmnopqrstuvwxyz':
                next_word = word[:i] + c + word[i+1:]
                if next_word in wordSet and next_word not in visited:
                    visited.add(next_word)
                    queue.append((next_word, steps + 1))
    return 0

print(ladderLength("hit", "cog", ["hot","dot","dog","lot","log","cog"]))


5


# **Assignment:4**

Q1. Create a dictionary of 5 students with their names as keys and marks as values. Print all the keys and values.


In [ ]:
# Create a dictionary of students with marks
students = {
    "Rahul": 85,
    "Priya": 92,
    "Amit": 78,
    "Neha": 89,
    "Suresh": 76
}

# Print all keys (names)
print("Names (keys):")
for name in students:
    print(name)
# Alternatively: print(list(students.keys()))

# Print all values (marks)
print("\nMarks (values):")
for mark in students.values():
    print(mark)
# Alternatively: print(list(students.values()))

# Print all key-value pairs
print("\nAll key-value pairs:")
for name, mark in students.items():
    print(name, ":", mark)


Names (keys):
Rahul
Priya
Amit
Neha
Suresh

Marks (values):
85
92
78
89
76

All key-value pairs:
Rahul : 85
Priya : 92
Amit : 78
Neha : 89
Suresh : 76


Q2. Write a program to count the frequency of each character in a given string using a dictionary.

In [ ]:
# Given string
s = "probin"

# Initialize an empty dictionary
frequency = {}

# Count frequency of each character
for char in s:
    if char in frequency:
        frequency[char] += 1
    else:
        frequency[char] = 1

# Print the frequency of each character
for char, count in frequency.items():
    print(f"'{char}' : {count}")


'p' : 1
'r' : 1
'o' : 1
'b' : 1
'i' : 1
'n' : 1


3. Create a dictionary with names as keys and ages as values. Print the name(s) of the oldest person(s).


In [ ]:
people = {
    "Sahil": 34,
    "Rahul": 56,
    "Saksham": 42,
    "Saiyam": 56,
    "Shrine": 29
}

# Find the maximum age
max_age = max(people.values())

# Find all names with the maximum age
oldest_names = [name for name, age in people.items() if age == max_age]

# Print the result
print("Oldest person(s):", ", ".join(oldest_names))


Oldest person(s): Rahul, Saiyam


Q4. Merge two dictionaries and print the merged dictionary.


In [ ]:
# Two dictionaries
dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}

# Merge dictionaries (Python 3.5+)
merged_dict = {**dict1, **dict2}

# Print the merged dictionary
print("Merged dictionary:", merged_dict)


Merged dictionary: {'a': 1, 'b': 2, 'c': 3, 'd': 4}


5. Create a dictionary where the keys are numbers between 1 and 10, and the values are their squares

In [ ]:
dict_squares = {i: i**2 for i in range(1, 11)}
print(dict_squares)



{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


6. Write a program that inverts a dictionary (i.e., swaps keys and values). Assume all values are unique.

In [ ]:
original_dict = {'a': 1, 'b': 2, 'c': 3, 'd': 4}

# Invert the dictionary
inverted_dict = {value: key for key, value in original_dict.items()}

print("Inverted dictionary:", inverted_dict)


Inverted dictionary: {1: 'a', 2: 'b', 3: 'c', 4: 'd'}


7. Given a nested dictionary of students and their subject-wise marks, calculate and print the average marks for each student.

In [ ]:
# Nested dictionary of students and their marks
students = {
    "Rahul": {"Maths": 85, "Science": 78, "English": 90},
    "Priya": {"Maths": 92, "Science": 88, "English": 86},
    "Amit": {"Maths": 76, "Science": 80, "English": 82}
}

# Calculate and print average marks for each student
for name, subjects in students.items():
    average = sum(subjects.values()) / len(subjects)
    print(f"{name}: Average marks = {average:.2f}")


Rahul: Average marks = 84.33
Priya: Average marks = 88.67
Amit: Average marks = 79.33


8. Write a program to group words by their length from a list using a dictionary.


In [ ]:
words = ["apple", "bat", "ball", "cat", "car", "dog", "elephant", "fish"]

# Dictionary to group words by length
length_to_words = {}

for word in words:
    length = len(word)
    if length in length_to_words:
        length_to_words[length].append(word)
    else:
        length_to_words[length] = [word]

# Print the result
for length, word_list in length_to_words.items():
    print(f"Words with {length} letters:", word_list)


Words with 5 letters: ['apple']
Words with 3 letters: ['bat', 'cat', 'car', 'dog']
Words with 4 letters: ['ball', 'fish']
Words with 8 letters: ['elephant']


Q9. Write a program to group words by their length from a list using a dictionary.


In [ ]:
words = ["apple", "bat", "ball", "cat", "car", "dog", "elephant", "fish"]

# Dictionary to group words by their length
length_groups = {}

for word in words:
    length = len(word)
    # If the length is already a key, append the word to the list
    if length in length_groups:
        length_groups[length].append(word)
    else:
        # Otherwise, create a new list for this length
        length_groups[length] = [word]

# Print the result
for length, group in sorted(length_groups.items()):
    print(f"Length {length}: {group}")


Length 3: ['bat', 'cat', 'car', 'dog']
Length 4: ['ball', 'fish']
Length 5: ['apple']
Length 8: ['elephant']


10. Create a program that takes a list of tuples (name, score) and builds a dictionary where each name is a key, and the value is a list of all their scores. Then calculate and print each person's average score.

In [ ]:
# List of tuples (name, score)
scores_list = [
    ("Alice", 85),
    ("Bob", 90),
    ("Alice", 92),
    ("Bob", 87),
    ("Charlie", 78),
    ("Alice", 89),
    ("Charlie", 82)
]

# Build the dictionary
name_to_scores = {}
for name, score in scores_list:
    if name in name_to_scores:
        name_to_scores[name].append(score)
    else:
        name_to_scores[name] = [score]

# Calculate and print average scores
for name, scores in name_to_scores.items():
    average = sum(scores) / len(scores)
    print(f"{name}: Average score = {average:.2f}")


Alice: Average score = 88.67
Bob: Average score = 88.50
Charlie: Average score = 80.00


# **Assignment:5**

Q1.WAP to make Pyramid

In [8]:
n = 5

for i in range(1, n + 1):
    print(' ' * (n - i) + '*' * (2 * i - 1))


    *
   ***
  *****
 *******
*********


Q2.Create a simple menu-drive program using while-loop.

In [18]:
while True:
    print("\n--- Menu ---")
    print("1. Say Hello")
    print("2. Display Current Date")
    print("3. Exit")

    choice = input("Enter your choice (1-3): ")

    if choice == '1':
        print("Hello!")
    elif choice == '2':
        from datetime import datetime
        print("Current date:", datetime.now().strftime("%Y-%m-%d"))
    elif choice == '3':
        print("Exiting the program. Goodbye!")
        break
    else:
        print("Invalid choice. Please try again.")



--- Menu ---
1. Say Hello
2. Display Current Date
3. Exit
Enter your choice (1-3): 3
Exiting the program. Goodbye!


Q3.Generate a pattern like:

Q4.Draw a sqaure pattern like star.

In [ ]:
n = 5

for i in range(n):
    for j in range(n):
        print("*", end=' ')
    print()


* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 


Q5.Draw a circular pattern like star.

In [17]:
import math

radius = 5

for y in range(-radius, radius + 1):
    for x in range(-radius, radius + 1):
        if x**2 + y**2 <= radius**2 + 0.5:
            print("*", end=' ')
        else:
            print(" ", end=' ')
    print()


          *           
    * * * * * * *     
  * * * * * * * * *   
  * * * * * * * * *   
  * * * * * * * * *   
* * * * * * * * * * * 
  * * * * * * * * *   
  * * * * * * * * *   
  * * * * * * * * *   
    * * * * * * *     
          *           


Q6.Draw a rectangular pattern like star.

In [ ]:
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))

for i in range(rows):
    for j in range(cols):
        print("*", end=" ")
    print()


Enter number of rows: 4
Enter number of columns: 6
* * * * * * 
* * * * * * 
* * * * * * 
* * * * * * 


Q7.Create a list ofeven numbers belonging to 'S' list.


# **Assignment:6**

Tuple Question

Q1. Write a Python program to create a tuple with different data types and print its type.

In [ ]:
# Creating a tuple with different data types
my_tuple = (42, "Hello", 3.14, True, [1, 2, 3], {'a': 1})

# Printing the tuple+
print("Tuple contents:", my_tuple)

# Printing the type
print("Type of the tuple:", type(my_tuple))


Tuple contents: (42, 'Hello', 3.14, True, [1, 2, 3], {'a': 1})
Type of the tuple: <class 'tuple'>


Q2. Given a tuple t = (10, 20, 30, 40, 50), write a program to access the second last element.

In [ ]:
t = (10, 20, 30, 40, 50)
second_last_element = t[-2]
print(second_last_element)


40


Q3. Write a program to count the number of times a given element appears in a tuple.

In [16]:
my_tuple = (10, 20, 30, 40, 20, 20, 70, 80)

# Element to count
element = 20

# Count occurrences using count()
count = my_tuple.count(element)

print(f"Number of occurrences of {element} = {count}")


Number of occurrences of 20 = 3


Q4. Write a program to convert a tuple of strings into a single string. Example: ('Python', 'is', 'fun') -->
'Python is fun'


In [ ]:
t = ('Python', 'is', 'fun')
s = ' '.join(t)
print(s)


Python is fun


Q5. Write a Python program to find the index of an element in a tuple

In [ ]:
t = (10, 20, 30, 40, 50)
element = 30

index = t.index(element)
print(f"Index of {element} is {index}")


Index of 30 is 2


Sets Question

Q6. Write a Python program to create two sets and perform union, intersection, and difference.

In [ ]:
# Create two sets
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

# Union: all elements from both sets
union = set1 | set2
print("Union:", union)

# Intersection: common elements in both sets
intersection = set1 & set2
print("Intersection:", intersection)

# Difference: elements in set1 but not in set2
difference = set1 - set2
print("Difference (set1 - set2):", difference)

# Optional: difference (set2 - set1)
difference2 = set2 - set1
print("Difference (set2 - set1):", difference2)


Union: {1, 2, 3, 4, 5, 6, 7, 8}
Intersection: {4, 5}
Difference (set1 - set2): {1, 2, 3}
Difference (set2 - set1): {8, 6, 7}


Q7. Write a program to check if a given element is present in a set or not.

In [15]:
my_set = {10, 20, 30, 40, 50}

# Element to check
element = 30

# Check if element is in the set
if element in my_set:
    print(f"{element} is present in the set")
else:
    print(f"{element} is not present in the set")


30 is present in the set


Q8. Write a program to remove duplicate elements from a list using a set.

In [ ]:
# Original list with duplicates
my_list = [1, 2, 2, 3, 4, 4, 5, 6, 6]

# Convert the list to a set to remove duplicates
unique_set = set(my_list)

# Convert the set back to a list (optional, if you need a list result)
unique_list = list(unique_set)

print("Original list:", my_list)
print("List after removing duplicates:", unique_list)


Original list: [1, 2, 2, 3, 4, 4, 5, 6, 6]
List after removing duplicates: [1, 2, 3, 4, 5, 6]


Q9. Write a Python program to find the symmetric difference between two sets.

In [ ]:
# Define two sets
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

# Symmetric difference using the ^ operator
sym_diff = set1 ^ set2

# Alternatively, using the .symmetric_difference() method
# sym_diff = set1.symmetric_difference(set2)

print("Symmetric difference:", sym_diff)


Symmetric difference: {1, 2, 3, 6, 7, 8}


Q10. Given a list of numbers, write a Python program to find all unique elements using sets.

In [ ]:
numbers = [1, 2, 2, 3, 4, 4, 5, 5]
unique_elements = set(numbers)
print("Unique elements:", unique_elements)


Unique elements: {1, 2, 3, 4, 5}


# **Assignment:7**

Q1. Write a function to find the factorial of a number using recursion.

In [ ]:
def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

number = int(input('Enter a number : '))
print(f"The factorial of {number} is {factorial(number)}")


Enter a number : 12
The factorial of 12 is 479001600


Q2.Write a function that checks whether a number is prime or not.

In [ ]:
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

number = int(input("Enter a number: "))
if is_prime(number):
    print(f"{number} is a prime number.")
else:
    print(f"{number} is not a prime number.")


Enter a number: 4
4 is not a prime number.


Q3.Create a function that takes a string as input and returns the number of vowels in it.

In [ ]:
def count_vowels(s):
    vowels = "aeiou"
    count = 0
    for char in s:
        if char in vowels:
            count += 1
    return count

string = input("Enter a string : ")
print("Number of vowels :", count_vowels(string))

Enter a string : Regulation
Number of vowels : 5


Q4.Write a function that accepts a list of numbers and returns the maximum and minimum values.

In [ ]:
def max_min(numbers):
    if not numbers:
        return (None, None)
    return (max(numbers), min(numbers))

numbers = [4, 2, 9, 7, 5]
result = max_min(numbers)
print("Maximum and minimum:", result)


Maximum and minimum: (9, 2)


Q5.Write a Python function to calculate the nth Fibonacci number using recursion.

In [ ]:
def fibonacci_number(n):
    if n < 0:
        raise ValueError("n must be a non-negative integer")
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci_number(n-1) + fibonacci_number(n-2)

n = int(input("Enter a number : "))
print(f"The {n}th Fibonacci number is :", fibonacci_number(n))


Enter a number : 22
The 22th Fibonacci number is : 17711


Q6.Create a function that accepts two numbers and returns their greatest common divisor (GCD).

In [ ]:
def gcd(a, b):
    if b == 0:
        return a
    else:
        return gcd(b, a % b)

print(gcd(44, 99))



11


Q7.Write a function that takes a list and returns a new list with only unique elements.

In [14]:
def unique_elements(lst):
    seen = set()
    result = []
    for item in lst:
        if item not in seen:
            seen.add(item)
            result.append(item)
    return result

my_list = [1, 2, 2, 3, 4, 4, 5]
print(unique_elements(my_list))


[1, 2, 3, 4, 5]


Q8 Write a function to count the frequency of each word in a given string.

In [ ]:
from collections import Counter

def word_frequency(s):
    return Counter(s.split())

print(word_frequency("apple orange banana apple orange apple"))



Counter({'apple': 3, 'orange': 2, 'banana': 1})


Q9.Write a function that takes a number and returns True if it is a palindrome, otherwise False.

In [ ]:
def is_palindrome(n):
    s = str(n)  # Convert the number to a string
    return s == s[::-1]  # Compare the string to its reverse

print(is_palindrome(12321))
print(is_palindrome(12345))


True
False


Q10.Create a function that takes a temperature in Celsius and returns it in Fahrenheit.

In [ ]:
def celsius_to_fahrenheit(celsius):
    return celsius * 9 / 5 + 32

# Example usage
print(celsius_to_fahrenheit(25))


77.0


# **Assignment:8**

Q1. Write a Python program to create a new text file and write the text 'Hello, File Handling!' to it.


In [ ]:
with open('example.txt', 'w') as file:
    file.write('Hello, File Handling!')

Q2. Write a Python program to read the contents of 'example.txt' and display them on the screen.


In [ ]:
# Step 1: Write to the file
with open('example.txt', 'w') as f:
    f.write('Hello, File Handling!')

# Step 2: Read from the file and display its contents
with open('example.txt', 'r') as f:
    contents = f.read()
    print(contents)


Hello, File Handling!


Q3. Write a Python program to count the number of words in a given text file.


In [ ]:
def count_words(filename):
    with open(filename, 'r') as file:
        text = file.read()
        words = text.split()
        return len(words)

# Example usage
word_count = count_words('example.txt')
print("Number of words in the file:", word_count)


Number of words in the file: 3


Q4. Write a Python program to read a file and print only those lines which start with the letter 'A'.


Q5. Write a Python program to merge the contents of two files into a third file.


Q6. Write a Python program that reads a text file and prints its content in reverse order (last line first).


Q7. Write a Python program to find and replace a word in a file (e.g., replace 'old' with 'new').


Q8. Write a Python program to create a log file and append timestamps whenever the program is run.


Q9. Write a Python program to store and read student records (name and marks) from a file.


Q10. Write a Python program to copy an image file (binary mode) from one location to another.

# **Assignment:9**

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [5]:
print(np.__version__)

2.0.2


Q1. Create a NumPy array with values from 1 to 10. Print the shape, dimension, and data type of the
array.


In [ ]:
import numpy as np

arr = np.arange(1, 11)
print("Array:", arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Data type:", arr.dtype)


Array: [ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Number of dimensions: 1
Data type: int64


Q2. Create a 3x3 NumPy array of all zeros and another of all ones. Then create a 3x3 identity matrix.


In [4]:
import numpy as np

# 3x3 array of all zeros
zeros_array = np.zeros((3, 3))
print("Zeros array:\n", zeros_array)

# 3x3 array of all ones
ones_array = np.ones((3, 3))
print("Ones array:\n", ones_array)

# 3x3 identity matrix
identity_matrix = np.identity(3)
print("Identity matrix:\n", identity_matrix)


Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q3. Generate an array of 15 random integers between 10 and 100 using np.random.randint. Reshape
it into a 3x5 matrix and print it.

In [6]:
import numpy as np

random_ints = np.random.randint(10, 101, size=15)

# 3x5 matrix
reshaped_matrix = random_ints.reshape(3, 5)

print(reshaped_matrix)


[[35 39 92 73 86]
 [17 66 14 45 68]
 [34 59 32 19 54]]


Q4. Create a NumPy array from 1 to 20. Extract every 3rd element starting from index 1 using slicing.


In [6]:
import numpy as np

# Create an array from 1 to 20 (inclusive)
arr = np.arange(1, 21)

# Extract every 3rd element starting from index 1 (i.e., arr[1], arr[4], arr[7], ...)
result = arr[1::3]

print(result)


[ 2  5  8 11 14 17 20]


Q5. Create two arrays: a = np.array([2, 4, 6, 8]) and b = np.array([1, 3, 5, 7]). Perform element-wise addition, multiplication, and compare which elements in a are greater than in b.


In [7]:
import numpy as np

a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])

# Element-wise addition
addition = a + b
print("Addition:", addition)

# Element-wise multiplication
multiplication = a * b
print("Multiplication:", multiplication)

# Compare which elements in a are greater than in b
comparison = a > b
print("a > b:", comparison)



Addition: [ 3  7 11 15]
Multiplication: [ 2 12 30 56]
a > b: [ True  True  True  True]


Q6. Create a NumPy array with 20 random values (0 to 1) using np.random.rand(). Find the mean,
median, standard deviation, min, and max.

In [8]:
import numpy as np

arr = np.random.rand(20)

mean = np.mean(arr)
median = np.median(arr)
std = np.std(arr)
min_val = np.min(arr)
max_val = np.max(arr)

print("Mean:", mean)
print("Median:", median)
print("Standard deviation:", std)
print("Minimum:", min_val)
print("Maximum:", max_val)


Mean: 0.5372462840767036
Median: 0.5033346678669836
Standard deviation: 0.2982185753592954
Minimum: 0.03615872078614912
Maximum: 0.9763608114302003


Q7. Given: arr = np.array([[3, 5], [7, 9]]). Find the sum across rows and columns using axis.


In [9]:
import numpy as np

arr = np.array([[3, 5], [7, 9]])

# Sum across rows (axis=0)
sum_rows = arr.sum(axis=0)
print("Sum across rows (axis=0):", sum_rows)

# Sum across columns (axis=1)
sum_cols = arr.sum(axis=1)
print("Sum across columns (axis=1):", sum_cols)


Sum across rows (axis=0): [10 14]
Sum across columns (axis=1): [ 8 16]


Q8. Create a NumPy array of numbers from 10 to 30. Filter and print only the even numbers using
boolean indexing.

In [10]:
import numpy as np

arr = np.arange(10, 31)

even_numbers = arr[arr % 2 == 0]

print("Even numbers from 10 to 30:")
print(even_numbers)


Even numbers from 10 to 30:
[10 12 14 16 18 20 22 24 26 28 30]


Q9. Generate an array of 10 random integers from 1 to 100. Replace all elements greater than 50 with
-1.

In [11]:
import numpy as np

arr = np.random.randint(1, 101, size=10)

print("Original array:")
print(arr)

arr[arr > 50] = -1

print("Modified array:")
print(arr)


Original array:
[20 92 57 98 10 17 77 38 32 24]
Modified array:
[20 -1 -1 -1 10 17 -1 38 32 24]


Q10. Create two arrays: x = np.array([[1, 2], [3, 4]]) and y = np.array([[5, 6], [7, 8]]). Stack them
vertically and horizontally, then flatten the result into a 1D array.

In [12]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

vstacked = np.vstack((x, y))
print("Vertically stacked:\n", vstacked)

hstacked = np.hstack((x, y))
print("Horizontally stacked:\n", hstacked)

flattened = vstacked.flatten()
print("Flattened (from vertical stack):\n", flattened)

flattened_h = hstacked.flatten()
print("Flattened (from horizontal stack):\n", flattened_h)


Vertically stacked:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontally stacked:
 [[1 2 5 6]
 [3 4 7 8]]
Flattened (from vertical stack):
 [1 2 3 4 5 6 7 8]
Flattened (from horizontal stack):
 [1 2 5 6 3 4 7 8]
